# Generated by Django 5.2.6 on 2025-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0002_department_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
