# Generated by Django 5.2.6 on 2025-09-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0003_studentprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(default="Not assigned", max_length=100, unique=True),
        ),
    ]
